### ISSUE TITLE
Missing installation information for Linux hosts

### ISSUE THREAD

**Issue by tbrowder** [librasteve/raku-PDF-Extract#1]

**Comment by tbrowder** [comment]
Installation on my Debian system:

    sudo aptitude install poppler-utils
    zef install PDF::Extract
    # error warning...
    # will add more info here

**Comment by librasteve** [comment]
hi @tbrowder - thanks for the feedback - it is not quite clear to me from your comment whether this is a gao in the docs or whether the module creates an error warning

please can you submit as a PR and I will accept"

**Comment by librasteve** [comment]
well this works on my ubuntu with apt-get ... so I will document that
