### ISSUE TITLE
Does not work for file paths with white spaces

### ISSUE THREAD

**Issue by antononcube** [librasteve/raku-PDF-Extract#3]
The PDF extraction does not work for file paths with white spaces.

Of course, a simple user workaround would be to do :

```raku
 my $extract = Extract.new(file => $file.subst(/(\s)/, { '\\' ~ $0.Str }):g);
```

But I think it is better to be handled by the package.

**Comment by librasteve** [comment]
ok - fixed this with better quoting in the qqx ... after some subst head scratching!

**Comment by antononcube** [comment]
Great, thanks! (And I removed my workaround in "Data::Importers".)

**Comment by jubilatious1** [comment]
Guessing this is a MacOS thing?

**Comment by antononcube** [comment]
> Guessing this is a MacOS thing?

Well, I observed the initial behavior on macOS.

**Comment by jubilatious1** [comment]
Just posting these to refresh my memory (Apple MacOS specific):

https://apple.stackexchange.com/questions/327097/open-a-file-with-spaces-in-the-name-in-terminal    
https://apple.stackexchange.com/questions/288934/spaces-in-a-folder-name    
https://superuser.com/questions/170087/in-the-osx-terminal-how-do-i-open-a-file-with-a-space-in-its-name    
https://stackoverflow.com/questions/10209870/properly-handle-lists-of-files-with-whitespace-in-filename    

Apple Support doc on how to handle filenames with spaces:
https://support.apple.com/en-euro/guide/terminal/apd3cf6fe02-3ec8-48f1-951f-866e52955fc8/mac


Here's a document from Apple called "Command Line Primer", that seems to lack recent updates to `zsh`:
https://developer.apple.com/library/archive/documentation/OpenSource/Conceptual/ShellScripting/CommandLInePrimer/CommandLine.html
