### ISSUE TITLE
Feature Request: return PDF text indexed to page/line numbers (in a map or hash?)

### ISSUE THREAD

**Issue by jubilatious1** [librasteve/raku-PDF-Extract#5]
Looking here:

https://pdfgrep.org/doc.html

It would be great to have the power of Raku regexes to search through PDFs by page_# and/or line_#.

Meaning that `PDF::Extract` would have to record that data while extracting, either into an array or into a hash.

(You could also imagine a large PDF saved into a hash-of-arrays:  with page_# as `key` and each page's lines stored in an array as the `value`).

I recognize this feature request is highly dependent on Poppler's capabilities.

TIA.

**Comment by librasteve** [comment]
this looks like a good idea in general - I do not have the bandwidth to check and implement whether poppler would support this ... I would be happy to review and merge a PR if you would like to propose this

**Comment by jubilatious1** [comment]
Thanks @librasteve for taking a look. Unfortunately writing a PR is above my pay-grade since I don't know `Poppler`.

https://unix.stackexchange.com/questions/776585/how-to-search-in-a-pdf-or-text-file-by-a-regex-pattern-and-output-locations-of-m

Honestly I saw a StackExchange question above answered with the `pdfgrep` unix executable:  https://pdfgrep.org 

I was hoping the Raku community had a ready-to-go alternative to `pdfgrep` (possibly a one-liner using your excellent  `PDF::Extract` module)? Maybe @dwarring and/or @tbrowder know a Raku solution using any of their excellent PDF modules?

Or does the Raku ecosystem need its own `PDF::Grep` module (hint,hint... )?

Thanks.

**Comment by dwarring** [comment]
Fwiw, I've avoided general text extraction. There's already plenty of mature solutions out there and also plenty of gnarly PDF files out there that are difficult to extract text on. 

What I am targeting, is the small, but slowly increasing number of  tagged PDF files. There are designed to support structured content and text extraction. See [PDF::Tags::Reader](https://raku.land/zef:dwarring/PDF::Tags::Reader).

Hmm, a `pdf-tag-grep` utility script could be nice....

**Comment by dwarring** [comment]
Btw, I notice that `PDF::Extract` has been integrated into [App::Rak](https://github.com/lizmat/App-Rak?tab=readme-ov-file) anyway.

**Comment by librasteve** [comment]
@dwarring - this mini module came from a short deadline project where I needed to get the text from a PDF, and after a superficial look at the previous raku PDF modules, I was not able to quickly locate a solution ... yep, this just does the text and (as you say) I chose to simple wrap the ```poppler``` package (I am not sure if that counts as one of the _mature_ solutions you mention, it is certainly quite limited) ... I would encourage anyone with more elaborate needs to explore the many other fantastic raku PDF modules...

**Comment by jubilatious1** [comment]
I see MacOS has an option to export PDFs as either "linearized PDF" or "PDF/A".

Maybe one of those might be helpful?
